import './types/augmentation.js'
export { createEIP155 } from './namespace.js'
export { EIP155Wallet } from './wallet.js'
export { EIP155_SCOPE } from './constants.js'
export type { EIP155Provider, EIP155Address, EIP155ChainId } from '@trustwallet/connect-eip155-types'
export type { CreateEIP155Options, EIP1193Provider } from './types/config.js'
