import './types/augmentation.js'
export { createBIP122 } from './namespace.js'
export { BitcoinStandardWallet } from './wallets/wallet-standard/wallet.js'
export { BIP122_SCOPE } from './constants.js'
export { mainnet, testnet, regtest } from './chains.js'
export type { BIP122Address, BIP122ChainId, BIP122Provider } from '@trustwallet/connect-bip122-types'
export type { CreateBIP122Options } from './types/config.js'
