import './types/augmentation.js'
export { createSolana } from './namespace.js'
export { SolanaStandardWallet } from './wallet.js'
export { SOLANA_SCOPE } from './constants.js'
export { mainnet, devnet, testnet } from './chains.js'
export type { SolanaAddress, SolanaChainId, SolanaProvider } from '@trustwallet/connect-solana-types'
export type { CreateSolanaOptions } from './types/config.js'
